from typing_extensions import TypedDict, List,Any

class QuizState(TypedDict):
    file_hash : str
    query : str
    chapter_name: str # chapter title
    summary: str # summary generated by summary state

    num_of_questions: int # total questions to ask
    quiz_type: str # mcq , true/False , fill in the blanks
    difficulty: str # hard , easy
    input_validate:bool

    question: str
    current_question: int
    score: int

    user_answer: str
    correct_answer: str # Correct answer for validation

    generate_questions: Any
    validate_answer : Any

    quiz_completed: bool # Whether the quiz has finished
    quiz_main_answer: str

    execution_plan : list[str]
